### ISSUE TITLE
Help needed for error message All AG GRID Enterprise features are unlocked

### ISSUE THREAD

**Issue by abhishekt572** [ag-grid/ag-grid-customise-theme#127]
I used the code provided here to setup up a local project the setup is fine and working well, but I can see messages on the console.  The message is attached here. Is there a problem if I use the given code base and change it as per my need. How can I remove these errors.
![image](https://user-images.githubusercontent.com/19290874/121730729-b5338d00-cb0d-11eb-88c3-1cb777610b9d.png)

**Comment by gportela85** [comment]
This is not an error, to use Ag Grid Enterprise, you need to buy a license. See [www.ag-grid.com/](https://www.ag-grid.com/license-pricing.php)
