### ISSUE TITLE
Angular example, please

### ISSUE THREAD

**Issue by twbutler** [ag-grid/ag-grid-customise-theme#2]
Can you please provide an Angular example?  I am using Angular 5.2.3 with angular-seed, and when I try to use a custom .scss file to modify the $cell-horizontal-padding variable to restore the original cell padding, the borders around and inside the table disappear and other styling inside the table appears to be disabled somehow. All that can be seen is the header names and the data in the columns/rows with a plain white background.  

Better yet, can you explain how to revert the cell horizontal padding without having to use SCSS?  This would be most ideal as we really do not need to use SCSS anywhere else in our project. 

Thanks...

**Comment by kultigin** [comment]
I don't seem to be able to change the variables either. I am in Angular-CLI
First I added to code  with bootstrap files
`
@import "~ag-grid/dist/styles/ag-grid";
@import "~ag-grid/dist/styles/ag-theme-bootstrap";

@import '~angular2-toaster/toaster';
// Core variables and mixins
@import "~bootstrap/scss/functions";

@import "variables-ark";
@import "~bootstrap/scss/bootstrap";

// Reset and dependencies

@import "glyphicons";
@import "ark-tag-theme";
@import "app";
@import "theme";`

Later I separated the file for ag-grid and loaded within CLI
` "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "analytics.js",
        "favicon.ico"
      ],
      "baseHref": "/emport/",
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "./assets/sass/bootstrap_cust.scss",
          "./assets/sass/ag-grid-custom.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],`

But the variables I wrote in the ag-grid-custom does not work even though the theme works.
`$cell-horizontal-padding: 5em;
$font-family: "Futura ND Book";
$font-size:16px;

@import "~ag-grid/dist/styles/ag-grid";
@import "~ag-grid/dist/styles/ag-theme-bootstrap";
`

**Comment by kultigin** [comment]
I realised my mistake, I am targeting wrong folder for .scss files if I want to edit...
