### ISSUE TITLE
Icon colors not reflected in Angular 6 and ag-grid v19

### ISSUE THREAD

**Issue by aryanisml** [ag-grid/ag-grid-customise-theme#5]
Hi,
Currently using the angular 6 with ag grid v19 community edition.
I followed the steps which mentioned on website to change the icon color however
couldn't able to change the icons. 
It would be great if you provide the example for it.

In Style.scss file
$ag-icons-path: '~ag-grid-community/src/styles/material-icons/';
$accent-color: blue !important;
import "~ag-grid-community/src/styles/ag-grid";
@import "~ag-grid-community/src/styles/ag-theme-material";

**Comment by marklbarlow** [comment]
This still seems to be an issue.  For now, using the dark theme I've had to manually add a " filter: invert(1);" on every icon to stop them from being black.

Is there a better example, or a fix that needs to be applied here?

**Comment by TheWeeezel** [comment]
Bump
